In [20]:

# import pandas lib as pd
import pandas as pd
from csv import excel
from pickletools import string1
import string
from urllib import response
from bs4 import BeautifulSoup
import requests, openpyxl
from urllib.parse import urljoin 
# read by default 1st sheet of an excel file
dataframe1 = pd.read_excel('IMDB.xlsx')
 
print(dataframe1)

     rank                      name  year  rate popularity  \
0       1  The Shawshank Redemption  1994   9.2         75
1       2             The Godfather  1972   9.2         23
2       3           The Dark Knight  2008   9.0        115
3       4     The Godfather Part II  1974   9.0         62
4       5              12 Angry Men  1957   8.9        394
..    ...                       ...   ...   ...        ...
245   246                   Aladdin  1992   8.0      1,034
246   247                    Gandhi  1982   8.0      3,063
247   248                  Jai Bhim  2021   8.0      2,683
248   249                  The Help  2011   8.0        761
249   250      Beauty and the Beast  1991   8.0      1,145

                      genres_list              director  \
0                           drama        Frank Darabont
1                    crime ,drama  Francis Ford Coppola
2            action ,crime ,drama     Christopher Nolan
3                    crime ,drama  Francis Ford Coppola
4                    crime ,drama          Sidney Lumet
..                            ...                   ...
245  animation ,adventure ,comedy          Ron Clements
246              biography ,drama  Richard Attenborough
247         crime ,drama ,mystery         T.J. Gnanavel
248                         drama           Tate Taylor
249    animation ,family ,fantasy        Gary Trousdale

                                             cast_list
0    Tim Robbins ,Morgan Freeman ,Bob Gunton ,Willi...
1    Marlon Brando ,Al Pacino ,James Caan ,Diane Ke...
2    Christian Bale ,Heath Ledger ,Aaron Eckhart ,M...
3    Al Pacino ,Robert De Niro ,Robert Duvall ,Dian...
4    Henry Fonda ,Lee J. Cobb ,Martin Balsam ,John ...
..                                                 ...
245  Scott Weinger ,Robin Williams ,Linda Larkin ,J...
246  Ben Kingsley ,John Gielgud ,Rohini Hattangadi ...
247  Suriya ,Lijo Mol Jose ,Manikandan K. ,Rajisha ...
248  Emma Stone ,Viola Davis ,Octavia Spencer ,Bryc...
249  Paige O'Hara ,Robby Benson ,Jesse Corti ,Rex E...

[250 rows x 8 columns]

In [21]:
web_site = "https://www.imdb.com/chart/top/"
response = requests.get(web_site)
html = response.content 


soup = BeautifulSoup(html, 'lxml')

In [22]:
movies = soup.find('tbody', class_="lister-list").find_all('tr')

In [23]:
name_list = [movie.find('td',class_="titleColumn").a.text for movie in movies]
rank_list = [movie.find('td',class_="titleColumn").get_text(strip=True).split('.')[0] for movie in movies]
year_list = [movie.find('td',class_="titleColumn").find('span').text.strip('()') for movie in movies]
rate_list = [movie.find('td', class_="ratingColumn imdbRating").strong.text for movie in movies]
popularity_list = []
director_list = []
genre_links = []

In [28]:
for movie in movies:  
    movie_url = urljoin(web_site, movie.find('td',class_="titleColumn").a['href'])
    response_page = requests.get(movie_url)
    html_page = response_page.content 
    soup_page = BeautifulSoup(html_page, 'lxml') 
         
    genre_links.append(soup_page.find('div',attrs={'data-testid': 'genres'}).find_all('a'))
    genres_list = [(a['href'].split("="))[1].split("&")[0] for a in genre_links]
    #genre_string = list_to_string([(a['href'].split("="))[1].split("&")[0] for a in genre_links])
            
    #director_list.append(soup_page.find('a',class_="ipc-metadata-list-item__list-content-item ipc-metadata-list-item__list-content-item--link").text)

TypeError: list indices must be integers or slices, not str

In [25]:
def list_to_string(list_):
    string = ', '.join([str(item) for item in list_])
    print(string)
    return string

In [ ]:
genres_list

In [17]:
movies = pd.DataFrame()
movies["movie name"] = name_list
movies["year"] = year_list
movies["rate"] = rate_list
#movies["cast"] = cast_string
#movies["popularity"] = popularity_list
movies["director"] = director_list
#movies["genres"] = genre_string
movies["rank"] = rank_list

In [18]:
movies

                   movie name  year rate              director rank
0    The Shawshank Redemption  1994  9.2        Frank Darabont    1
1               The Godfather  1972  9.2  Francis Ford Coppola    2
2             The Dark Knight  2008  9.0     Christopher Nolan    3
3       The Godfather Part II  1974  9.0  Francis Ford Coppola    4
4                12 Angry Men  1957  8.9          Sidney Lumet    5
..                        ...   ...  ...                   ...  ...
245                  Jai Bhim  2021  8.0         T.J. Gnanavel  246
246                   Aladdin  1992  8.0          Ron Clements  247
247                    Gandhi  1982  8.0  Richard Attenborough  248
248                  The Help  2011  8.0           Tate Taylor  249
249      Beauty and the Beast  1991  8.0        Gary Trousdale  250

[250 rows x 5 columns]